-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION meetingApp.fullName(user_row meetingApp.users) RETURNS text LANGUAGE sql STABLE AS $function$ SELECT user_row.name || ' ' || user_row.surname $function$;
