const countries = [
	{
		id: 1,
		name: "France",
		code: "FR",
		continent_code: "EU",
		emoji: "https://flagsapi.com/FR/flat/64.png",
		capital: "Paris",
		languages: [1],
	},
	{
		id: 2,
		name: "United States",
		code: "US",
		continent_code: "NA",
		emoji: "https://flagsapi.com/US/flat/64.png",
		capital: "Washington, D.C.",
		languages: [2],
	},
	{
		id: 3,
		name: "Canada",
		code: "CA",
		continent_code: "NA",
		emoji: "https://flagsapi.com/CA/flat/64.png",
		capital: "Ottawa",
		languages: [2, 1],
	},
	{
		id: 4,
		name: "Germany",
		code: "DE",
		continent_code: "EU",
		emoji: "https://flagsapi.com/DE/flat/64.png",
		capital: "Berlin",
		languages: [3],
	},
	{
		id: 5,
		name: "United Kingdom",
		code: "GB",
		continent_code: "EU",
		emoji: "https://flagsapi.com/GB/flat/64.png",
		capital: "London",
		languages: [2],
	},
	{
		id: 6,
		name: "Australia",
		code: "AU",
		continent_code: "OC",
		emoji: "https://flagsapi.com/AU/flat/64.png",
		capital: "Canberra",
		languages: [2],
	},
	{
		id: 7,
		name: "Japan",
		code: "JP",
		continent_code: "AS",
		emoji: "https://flagsapi.com/JP/flat/64.png",
		capital: "Tokyo",
		languages: [6],
	},
	{
		id: 8,
		name: "China",
		code: "CN",
		continent_code: "AS",
		emoji: "https://flagsapi.com/CN/flat/64.png",
		capital: "Beijing",
		languages: [7],
	},
	{
		id: 9,
		name: "India",
		code: "IN",
		continent_code: "AS",
		emoji: "https://flagsapi.com/IN/flat/64.png",
		capital: "New Delhi",
		languages: [8, 2],
	},
	{
		id: 10,
		name: "Brazil",
		code: "BR",
		continent_code: "SA",
		emoji: "https://flagsapi.com/BR/flat/64.png",
		capital: "Brasília",
		languages: [9],
	},
	{
		id: 11,
		name: "Argentina",
		code: "AR",
		continent_code: "SA",
		emoji: "https://flagsapi.com/AR/flat/64.png",
		capital: "Buenos Aires",
		languages: [4],
	},
	{
		id: 12,
		name: "South Africa",
		code: "ZA",
		continent_code: "AF",
		emoji: "https://flagsapi.com/ZA/flat/64.png",
		capital: "Pretoria, Bloemfontein, and Cape Town",
		languages: [11, 2],
	},
	{
		id: 13,
		name: "Egypt",
		code: "EG",
		continent_code: "AF",
		emoji: "https://flagsapi.com/EG/flat/64.png",
		capital: "Cairo",
		languages: [12],
	},
	{
		id: 14,
		name: "Russia",
		code: "RU",
		continent_code: "EU",
		emoji: "https://flagsapi.com/RU/flat/64.png",
		capital: "Moscow",
		languages: [13],
	},
	{
		id: 15,
		name: "South Korea",
		code: "KR",
		continent_code: "AS",
		emoji: "https://flagsapi.com/KR/flat/64.png",
		capital: "Seoul",
		languages: [10],
	},
	{
		id: 16,
		name: "Mexico",
		code: "MX",
		continent_code: "NA",
		emoji: "https://flagsapi.com/MX/flat/64.png",
		capital: "Mexico City",
		languages: [4],
	},
	{
		id: 17,
		name: "Italy",
		code: "IT",
		continent_code: "EU",
		emoji: "https://flagsapi.com/IT/flat/64.png",
		capital: "Rome",
		languages: [5],
	},
	{
		id: 18,
		name: "Spain",
		code: "ES",
		continent_code: "EU",
		emoji: "https://flagsapi.com/ES/flat/64.png",
		capital: "Madrid",
		languages: [4],
	},
	{
		id: 19,
		name: "Netherlands",
		code: "NL",
		continent_code: "EU",
		emoji: "https://flagsapi.com/NL/flat/64.png",
		capital: "Amsterdam",
		languages: [15],
	},
	{
		id: 20,
		name: "Turkey",
		code: "TR",
		continent_code: "AS",
		emoji: "https://flagsapi.com/TR/flat/64.png",
		capital: "Ankara",
		languages: [14],
	},
];

const languages = [
	{
		id: 1,
		code: "fr",
		native: "Français",
		name: "French",
	},
	{
		id: 2,
		code: "en",
		native: "English",
		name: "English",
	},
	{
		id: 3,
		code: "de",
		native: "Deutsch",
		name: "German",
	},
	{
		id: 4,
		code: "es",
		native: "Español",
		name: "Spanish",
	},
	{
		id: 5,
		code: "it",
		native: "Italiano",
		name: "Italian",
	},
	{
		id: 6,
		code: "ja",
		native: "日本語",
		name: "Japanese",
	},
	{
		id: 7,
		code: "zh",
		native: "中文",
		name: "Chinese",
	},
	{
		id: 8,
		code: "hi",
		native: "हिन्दी",
		name: "Hindi",
	},
	{
		id: 9,
		code: "pt",
		native: "Português",
		name: "Portuguese",
	},
	{
		id: 10,
		code: "ko",
		native: "한국어",
		name: "Korean",
	},
	{
		id: 11,
		code: "af",
		native: "Afrikaans",
		name: "Afrikaans",
	},
	{
		id: 12,
		code: "ar",
		native: "العربية",
		name: "Arabic",
	},
	{
		id: 13,
		code: "ru",
		native: "Русский",
		name: "Russian",
	},
	{
		id: 14,
		code: "tr",
		native: "Türkçe",
		name: "Turkish",
	},
	{
		id: 15,
		code: "nl",
		native: "Nederlands",
		name: "Dutch",
	},
];

const continents = [
    {id: 1, name: "Africa", code: "AF"},
    {id: 2, name: "Antarctica", code: "AN"},
    {id: 3, name: "Asia", code: "AS"},
    {id: 4, name: "Europe", code: "EU"},
    {id: 5, name: "North America", code: "NA"}, 
    {id: 6, name: "Oceania", code: "OC"},
    {id: 7, name: "South America", code: "SA"},
]

module.exports = { countries, languages, continents };
