const countries = [
	{
		id: 1,
		name: "France",
		code: "FR",
		continent_code: "EU",
		emoji: "https://flagsapi.com/FR/flat/64.png",
	},
	{
		id: 2,
		name: "United States",
		code: "US",
		continent_code: "NA",
		emoji: "https://flagsapi.com/US/flat/64.png",
	},
	{
		id: 3,
		name: "Canada",
		code: "CA",
		continent_code: "NA",
		emoji: "https://flagsapi.com/CA/flat/64.png",
	},
	{
		id: 4,
		name: "Germany",
		code: "DE",
		continent_code: "EU",
		emoji: "https://flagsapi.com/DE/flat/64.png",
	},
	{
		id: 5,
		name: "United Kingdom",
		code: "GB",
		continent_code: "EU",
		emoji: "https://flagsapi.com/GB/flat/64.png",
	},
	{
		id: 6,
		name: "Australia",
		code: "AU",
		continent_code: "OC",
		emoji: "https://flagsapi.com/AU/flat/64.png",
	},
	{
		id: 7,
		name: "Japan",
		code: "JP",
		continent_code: "AS",
		emoji: "https://flagsapi.com/JP/flat/64.png",
	},
	{
		id: 8,
		name: "China",
		code: "CN",
		continent_code: "AS",
		emoji: "https://flagsapi.com/CN/flat/64.png",
	},
	{
		id: 9,
		name: "India",
		code: "IN",
		continent_code: "AS",
		emoji: "https://flagsapi.com/IN/flat/64.png",
	},
	{
		id: 10,
		name: "Brazil",
		code: "BR",
		continent_code: "SA",
		emoji: "https://flagsapi.com/BR/flat/64.png",
	},
	{
		id: 11,
		name: "Argentina",
		code: "AR",
		continent_code: "SA",
		emoji: "https://flagsapi.com/AR/flat/64.png",
	},
	{
		id: 12,
		name: "South Africa",
		code: "ZA",
		continent_code: "AF",
		emoji: "https://flagsapi.com/ZA/flat/64.png",
	},
	{
		id: 13,
		name: "Egypt",
		code: "EG",
		continent_code: "AF",
		emoji: "https://flagsapi.com/EG/flat/64.png",
	},
	{
		id: 14,
		name: "Russia",
		code: "RU",
		continent_code: "EU",
		emoji: "https://flagsapi.com/RU/flat/64.png",
	},
	{
		id: 15,
		name: "South Korea",
		code: "KR",
		continent_code: "AS",
		emoji: "https://flagsapi.com/KR/flat/64.png",
	},
	{
		id: 16,
		name: "Mexico",
		code: "MX",
		continent_code: "NA",
		emoji: "https://flagsapi.com/MX/flat/64.png",
	},
	{
		id: 17,
		name: "Italy",
		code: "IT",
		continent_code: "EU",
		emoji: "https://flagsapi.com/IT/flat/64.png",
	},
	{
		id: 18,
		name: "Spain",
		code: "ES",
		continent_code: "EU",
		emoji: "https://flagsapi.com/ES/flat/64.png",
	},
	{
		id: 19,
		name: "Netherlands",
		code: "NL",
		continent_code: "EU",
		emoji: "https://flagsapi.com/NL/flat/64.png",
	},
	{
		id: 20,
		name: "Turkey",
		code: "TR",
		continent_code: "AS",
		emoji: "https://flagsapi.com/TR/flat/64.png",
	},
];

module.exports = countries;
